### ISSUE TITLE
Update to JupyterLab 4.0

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/retrolab#303]
### Problem

As proposed in https://github.com/jupyter/enhancement-proposals/pull/79, RetroLab is meant to become Notebook v7.

The JEP proposes to ship have Notebook v7 and JupyterLab 4 work well together, so users can seamlessly switch between the two interfaces.

So we should soon start looking into updating to the latest `4.0` pre-release of JupyterLab.

### Proposed Solution

We update the `@jupyterlab` packages to `4.0.0-alpha.x` (or newer), and the Python package to `4.0.0ax` (or newer).

**Comment by jtpio** [comment]
## TODO when updating to 4.0

- [ ] Reuse upstream top area spacer from https://github.com/jupyterlab/jupyterlab/pull/11654. So the spacer is placed at the same rank as in JupyterLab, and federated extensions can place items in the top area in a consistent manner

**Comment by jtpio** [comment]
It should be possible to do quickstart the update with:

```
jlpm run update:dependency --regex @jupyterlab/ next
jlpm run integrity
```

**Comment by davidbrochart** [comment]
At first sight it errors out with:
```
    lerna ERR! yarn run build exited 1 in '@retrolab/lab-extension'
    lerna ERR! yarn run build stdout:
    $ jlpm run build:lib && jlpm run build:labextension:dev
    $ tsc
    src/index.ts(67,5): error TS2322: Type 'Token<IRetroShell>' is not assignable to type 'Token<any>'.
      Types have separate declarations of a private property '_tokenStructuralPropertyT'.
```

**Comment by jtpio** [comment]
Maybe the `@lumino` packages could also be updated to the `latest`.

**Comment by davidbrochart** [comment]
Running the following doesn't help:
```
jlpm run update:dependency --regex @lumino/ latest
```

**Comment by jtpio** [comment]
Ah ok maybe I can give it a try locally to try to reproduce.

Otherwise maybe `rm -rf node_modules` to clean up the previous dependencies might help.

**Comment by davidbrochart** [comment]
Already did, but maybe I'm missing something.
